// Builds supabase/seed.sql from supabase/seed/topic-matrix.csv. (TOPIC-MATRIX.md)
// The CSV is the source of truth — edit it in a spreadsheet, then run `pnpm db:seed:build`.

import { readFileSync, writeFileSync } from "node:fs";

const CSV_PATH = "supabase/seed/topic-matrix.csv";
const OUT_PATH = "supabase/seed.sql";

// TOPIC-MATRIX.md §1. Order here is the nav order.
const categories = [
  ["sleep", "Sleep", "Sleep quality, timing, night waking, shift work"],
  ["digestion", "Digestion", "Gut, bloating, appetite, food reactions"],
  ["movement", "Movement", "Exercise, joints, posture, desk-body problems"],
  ["food", "Food", "Nutrition, hydration, energy"],
  ["mind", "Mind", "Stress, focus, mood, burnout — non-clinical"],
  ["everyday-body", "Everyday Body", "Skin, hair, nails, teeth, eyes, ears"],
  ["prevention", "Prevention", "Screening awareness, ageing, health numbers"],
];

const COLUMNS = ["category", "subtopic", "angle", "audience", "format", "target_query", "priority"];

const sql = (value) => `'${String(value).replaceAll("'", "''")}'`;

// The seed has no quoted fields; fail loudly rather than mis-split one if that changes.
function parseCsv(text) {
  const [header, ...lines] = text.trim().split(/\r?\n/);
  if (header !== COLUMNS.join(",")) {
    throw new Error(`Unexpected CSV header: ${header}\nExpected: ${COLUMNS.join(",")}`);
  }
  return lines.map((line, index) => {
    if (line.includes('"')) throw new Error(`Line ${index + 2}: quoted fields are not supported`);
    const cells = line.split(",");
    if (cells.length !== COLUMNS.length) {
      throw new Error(`Line ${index + 2}: expected ${COLUMNS.length} fields, got ${cells.length}`);
    }
    return Object.fromEntries(COLUMNS.map((column, i) => [column, cells[i].trim()]));
  });
}

const rows = parseCsv(readFileSync(CSV_PATH, "utf8"));
const knownNames = new Set(categories.map(([, name]) => name));
for (const row of rows) {
  if (!knownNames.has(row.category)) throw new Error(`Unknown category: ${row.category}`);
}

const categoryValues = categories
  .map(
    ([slug, name, description], i) =>
      `  (${sql(slug)}, ${sql(name)}, ${sql(description)}, ${i + 1})`,
  )
  .join(",\n");

const matrixValues = rows
  .map(
    (r) =>
      `  (${sql(r.category)}, ${sql(r.subtopic)}, ${sql(r.angle)}, ${sql(r.audience)}, ${sql(r.format)}, ${sql(r.target_query)}, ${Number(r.priority)})`,
  )
  .join(",\n");

const output = `-- GENERATED by scripts/build-seed.mjs from ${CSV_PATH}. Do not edit by hand.
-- ${categories.length} categories, ${rows.length} topic matrix cells.

insert into public.categories (slug, name, description, sort_order) values
${categoryValues}
on conflict (slug) do update
  set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;

insert into public.topic_matrix (category_id, subtopic, angle, audience, format, target_query, priority)
select c.id, v.subtopic, v.angle, v.audience, v.format, v.target_query, v.priority
from (values
${matrixValues}
) as v (category, subtopic, angle, audience, format, target_query, priority)
join public.categories c on c.name = v.category
on conflict (target_query) do nothing;
`;

writeFileSync(OUT_PATH, output);
console.log(`Wrote ${OUT_PATH}: ${categories.length} categories, ${rows.length} cells.`);
