-- 0008_add_post_covers — real cover images. (Reverses DESIGN.md §6's "no covers", 2026-09-25.)
--
-- Covers are AI-generated by the pipeline (M4) or uploaded by staff from the editor. Files live in
-- the public `covers` bucket; the post stores the object path plus what's needed to render it
-- without layout shift (intrinsic size) and to describe it honestly (alt text, source).

alter table public.posts
  add column cover_path   text,
  add column cover_alt    text,
  add column cover_width  integer,
  add column cover_height integer,
  -- 'ai': generated by the pipeline — the article credits it as AI-generated. 'upload': staff.
  add column cover_source text check (cover_source in ('ai', 'upload')),
  add constraint posts_cover_complete check (
    cover_path is null
    or (
      char_length(btrim(cover_alt)) > 0
      and cover_width > 0
      and cover_height > 0
      and cover_source is not null
    )
  );

-- ---------------------------------------------------------------------------
-- Storage. Public bucket: anyone can fetch a cover by URL (they're shown on public pages) —
-- public URLs don't go through RLS. SELECT is staff-only, so the bucket can't be listed by
-- anyone else; Storage also needs it to find objects when replacing or deleting them.
-- Only staff write; the pipeline uses the service role.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('covers', 'covers', true, 5242880, array['image/jpeg', 'image/png', 'image/webp', 'image/avif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "covers: staff read"
  on storage.objects for select to authenticated
  using (bucket_id = 'covers' and (select private.is_staff()));

create policy "covers: staff upload"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'covers' and (select private.is_staff()));

create policy "covers: staff replace"
  on storage.objects for update to authenticated
  using (bucket_id = 'covers' and (select private.is_staff()))
  with check (bucket_id = 'covers' and (select private.is_staff()));

create policy "covers: staff delete"
  on storage.objects for delete to authenticated
  using (bucket_id = 'covers' and (select private.is_staff()));
